### ISSUE TITLE
Public posts cannot be found when searching by title

### ISSUE THREAD

**Issue by edisim** [PostOwl/postowl#23]
https://github.com/PostOwl/postowl/blob/18a00bc485191df756e51038acef4b406acf0cd0/src/lib/api.js#L269

I don't know if this was intentionally implemented this way, but I was a bit confused when I tested the search function and entering the title didn't return a result.

**Comment by edisim** [comment]
Sorry, just realized I should've opened a discussion instead.

**Comment by keybits** [comment]
Thanks, that is unintentional. We'll get it fixed :-)

**Comment by michael** [comment]
Fixed via https://github.com/PostOwl/postowl/commit/345eb56633c03657ca24815497395d3c4f821825
