### ISSUE TITLE
Images - make getting a cursor easier

### ISSUE THREAD

**Issue by michael** [PostOwl/postowl#35]
Things that aren't easy for people:

1. Start a new post, try to add a picture - the add image control is greyed out until some text is added
2. Insert a new picture, then type. Image disappears.
3. Insert a new picture try to get a cursor by pressimg right arrow when image is selected. Start typing, text appears above image not below.

**Comment by michael** [comment]
Solution proposal:
- We adjust the prosemirror model that the first element must not be an image: This way you can't end up with a situation that you can't place the cursor before the image.
- In order to get a cursor after inserting an image, we could always insert a new paragraph after the image, and put the cursor there. That way you can continue writing after inserting an image.

**Comment by keybits** [comment]
Sounds good to me 😄

**Comment by keybits** [comment]
Marking as done with 2eadc31ae1fe37c50b3ff5d6fbaac80426eeff8d and f10f43af3c0cacb81533781785f98a6681d9411b
